### ISSUE TITLE
Allow run_script to return?

### ISSUE THREAD

**Issue by kanflo** [davea/mqttwrapper#1]
This library fits my MQTT needs nicely. I would however like ```run_script(...)``` to be able to spawn a thread and then return when calling eg. ```run_script(callback, ..., non_blocking = True)```. Would you be interested in a PR for this? I know I could start a thread on my own but it would be convenient not to ;)

**Comment by davea** [comment]
Hi, thanks for your interest. That sounds like a good feature, I'd be keen to hear more about your use case. Please feel free to submit a PR. :)

**Comment by kanflo** [comment]
Raised a PR, looking forward to your input.

**Comment by davea** [comment]
Fixed in #2. 👍
